# Generated by Django 3.2.4 on 2021-07-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='students',
            new_name='class_name',
        ),
    ]
